version: '3.4'

services:

  react-app:
    container_name: react-app
    build:
      context: ./services/react-app
      dockerfile: Dockerfile-prod
    expose:
      - 80
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - flask-app
    links:
      - flask-app
  
  flask-app:
    container_name: flask-app
    build:
      context: ./services/flask-app
      dockerfile: Dockerfile-prod
    volumes:
      - ./services/flask-app:/usr/src/app
    expose:
      - 5000
    environment: 
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_HOST=mongodb

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask-app
      - react-app

  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-prod
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - flask-app

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
     - "27017:27017"