version: '3.4'

services:

  react-app:
    container_name: react-app
    build:
      context: ./services/react-app
      dockerfile: Dockerfile-dev
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - flask-app
    links:
      - flask-app
  
  flask-app:
    container_name: flask-app
    build:
      context: ./services/flask-app
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/flask-app:/usr/src/app
    expose:
      - 5000
    environment: 
      - FLASK_DEBUG=1 
      - DATABASE_HOST=mongodb
      - APP_SETTINGS=project.config.DevelopmentConfig 

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask-app
      - react-app

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
     - "27017:27017"
  
  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-dev
    volumes:
      - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - '3008:8080'
    environment:
      - URL=swagger.json
    depends_on:
      - flask-app
